# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myProto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='myProto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmyProto.proto\".\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nnewmessage\x18\x02 \x01(\t\"\x1a\n\nCoffeeType\x12\x0c\n\x04name\x18\x01 \x01(\t2o\n\x0b\x43offeeTypes\x12+\n\x10GetOneCoffeeType\x12\x08.Request\x1a\x0b.CoffeeType\"\x00\x12\x33\n\x16GetMultipleCoffeeTypes\x12\x08.Request\x1a\x0b.CoffeeType\"\x00\x30\x01\x62\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='Request.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newmessage', full_name='Request.newmessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=63,
)


_COFFEETYPE = _descriptor.Descriptor(
  name='CoffeeType',
  full_name='CoffeeType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CoffeeType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['CoffeeType'] = _COFFEETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'myProto_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

CoffeeType = _reflection.GeneratedProtocolMessageType('CoffeeType', (_message.Message,), {
  'DESCRIPTOR' : _COFFEETYPE,
  '__module__' : 'myProto_pb2'
  # @@protoc_insertion_point(class_scope:CoffeeType)
  })
_sym_db.RegisterMessage(CoffeeType)



_COFFEETYPES = _descriptor.ServiceDescriptor(
  name='CoffeeTypes',
  full_name='CoffeeTypes',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=93,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOneCoffeeType',
    full_name='CoffeeTypes.GetOneCoffeeType',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_COFFEETYPE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetMultipleCoffeeTypes',
    full_name='CoffeeTypes.GetMultipleCoffeeTypes',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_COFFEETYPE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COFFEETYPES)

DESCRIPTOR.services_by_name['CoffeeTypes'] = _COFFEETYPES

# @@protoc_insertion_point(module_scope)
