# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import myProto_pb2 as myProto__pb2


class CoffeeTypesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOneCoffeeType = channel.unary_unary(
        '/CoffeeTypes/GetOneCoffeeType',
        request_serializer=myProto__pb2.Request.SerializeToString,
        response_deserializer=myProto__pb2.CoffeeType.FromString,
        )
    self.GetMultipleCoffeeTypes = channel.unary_stream(
        '/CoffeeTypes/GetMultipleCoffeeTypes',
        request_serializer=myProto__pb2.Request.SerializeToString,
        response_deserializer=myProto__pb2.CoffeeType.FromString,
        )


class CoffeeTypesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOneCoffeeType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMultipleCoffeeTypes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CoffeeTypesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOneCoffeeType': grpc.unary_unary_rpc_method_handler(
          servicer.GetOneCoffeeType,
          request_deserializer=myProto__pb2.Request.FromString,
          response_serializer=myProto__pb2.CoffeeType.SerializeToString,
      ),
      'GetMultipleCoffeeTypes': grpc.unary_stream_rpc_method_handler(
          servicer.GetMultipleCoffeeTypes,
          request_deserializer=myProto__pb2.Request.FromString,
          response_serializer=myProto__pb2.CoffeeType.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CoffeeTypes', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
